### ISSUE TITLE
Editor does not work with Horizontal Stack/Unable to edit any part of card after YAML editing

### ISSUE THREAD

**Issue by TheOneOgre** [MelleD/lovelace-expander-card#231]
Recently found this card out of a necessity for an expander card. I am trying to utilize this card with the Horizontal Stack card and am experiencing major issues with this card while trying to make it work.

When adding the card, using the visual editor works fine, up until the point Horizontal Card is selected. Once it is selected, you can add cards to it via the UI, but these will not be saved, nor will the horizontal card itself be saved to the YAML of the expander card, it simply leaves "card:[]" at the end of the YAML file.

After this line is added to the YAML, it seems none of the UI will make further edits to the card/YAML and all changes will be lost after clicking save. The only way to edit the card moving forward is via YAML directly in the code editor, which does work but is much more difficult.  I know this can't be intended.

I am using HA 2024.8.0 with frontend 20240806.1.
lovelace-expander-card 1.6.5
and have tried this with the latest Chrome browser on Windows, as well as the native android HA companion app, same results.

**Comment by frm1001xplrr** [comment]
I'm seeing similar issue with Mushroom Light cards. After the initial setup of the card no further configuring in the UI has any effect or will save. Here's a screengrab: https://app.screencast.com/TVPoV8vHinObF


Core 2024.8.2
Supervisor 2024.08.0
Operating System 12.4
Frontend 20240809.0
Expander 1.6.5
Google Chrome 127.0.6533.120 (Official Build) (64-bit) in Guest mode

**Comment by frm1001xplrr** [comment]
["Remove UI editor, because it works not pretty well."](https://github.com/MelleD/lovelace-expander-card/pull/233#issue-2472855924)
Yikes :(

**Comment by TheOneOgre** [comment]
What? The fix is to just remove the config editor all together?????? I couldn't even have figured out how to properly integrate the yaml if the config didn't start it to begin with.

Maybe don't close this issue because it's technically not fixed? So that if someone wanted to make a PR to fix this, they'd have some reference problems?

**Comment by MelleD** [comment]
There are several discussion to remove the config editor. So for now this is closed also see the README

If you are not familiar with yaml you have a lot of options:
a) use another card with config editor 
b) contribute the config editor here in this project 
c) open a feature request for an editor. Hope and wait till somebody will contribute an editor
d) learn yaml
f) fork it and start an own project 
g) improve the documentation and add some examples

Whatever you want :)

If there are new editor and the issue comes again we can reopen it, but for now currently no editor is maintained till somebody is contribute it.
